# -*- encoding: utf-8 -*-
"""
Tests for KGQL Neo4j Cypher exporter.

Tests export_neo4j() and export_neo4j_merge() for generating
valid Cypher CREATE/MERGE statements.
"""

import pytest

from kgql.export.graph import (
    PropertyGraph,
    GraphNode,
    GraphEdge,
    NodeType,
)
from kgql.export.neo4j import (
    export_neo4j,
    export_neo4j_merge,
    _cypher_escape,
)


@pytest.fixture
def sample_graph():
    """Create a sample graph for testing."""
    g = PropertyGraph()
    g.add_node(GraphNode(
        said="ESAID1",
        node_type=NodeType.CREDENTIAL,
        issuer="EAID1",
        schema="ESCHEMA1",
    ))
    g.add_node(GraphNode(
        said="ESAID2",
        node_type=NodeType.CREDENTIAL,
        issuer="EAID2",
        schema="ESCHEMA1",
    ))
    g.add_node(GraphNode(
        said="EAID1",
        node_type=NodeType.IDENTIFIER,
        label="Master AID",
    ))
    g.add_edge(GraphEdge(
        source_said="ESAID1",
        target_said="ESAID2",
        edge_type="acdc",
        operator="I2I",
    ))
    g.add_edge(GraphEdge(
        source_said="EAID1",
        target_said="ESAID1",
        edge_type="iss",
        operator="ANY",
    ))
    return g


class TestExportNeo4j:
    """Tests for export_neo4j()."""

    def test_export_contains_create(self, sample_graph):
        """Test that output contains CREATE statements."""
        cypher = export_neo4j(sample_graph)
        assert "CREATE" in cypher

    def test_export_contains_header(self, sample_graph):
        """Test that output contains comment header."""
        cypher = export_neo4j(sample_graph)
        assert "// Generated by KGQL" in cypher
        assert "Nodes: 3" in cypher
        assert "Edges: 2" in cypher

    def test_export_no_header(self, sample_graph):
        """Test export without header."""
        cypher = export_neo4j(sample_graph, include_header=False)
        assert "//" not in cypher.split("\n")[0]
        assert "CREATE" in cypher

    def test_export_node_labels(self, sample_graph):
        """Test that nodes have correct labels."""
        cypher = export_neo4j(sample_graph)
        assert ":Credential" in cypher
        assert ":Identifier" in cypher

    def test_export_node_properties(self, sample_graph):
        """Test that nodes have SAID property."""
        cypher = export_neo4j(sample_graph)
        assert "said: 'ESAID1'" in cypher
        assert "issuer: 'EAID1'" in cypher

    def test_export_edge_relationships(self, sample_graph):
        """Test that edges create relationships."""
        cypher = export_neo4j(sample_graph)
        assert "[:ACDC" in cypher
        assert "[:ISS" in cypher

    def test_export_edge_properties(self, sample_graph):
        """Test that edges have properties."""
        cypher = export_neo4j(sample_graph)
        assert "operator: 'I2I'" in cypher

    def test_export_custom_prefix(self, sample_graph):
        """Test custom variable prefix."""
        cypher = export_neo4j(sample_graph, variable_prefix="node")
        assert "(node0:" in cypher
        assert "(node1:" in cypher


class TestExportNeo4jMerge:
    """Tests for export_neo4j_merge()."""

    def test_export_contains_merge(self, sample_graph):
        """Test that output contains MERGE statements."""
        cypher = export_neo4j_merge(sample_graph)
        assert "MERGE" in cypher
        assert "CREATE" not in cypher

    def test_export_merge_header(self, sample_graph):
        """Test MERGE header mentions merge mode."""
        cypher = export_neo4j_merge(sample_graph)
        assert "MERGE mode" in cypher


class TestCypherEscape:
    """Tests for Cypher string escaping."""

    def test_escape_single_quote(self):
        """Test escaping single quotes."""
        assert _cypher_escape("It's a test") == "It\\'s a test"

    def test_escape_backslash(self):
        """Test escaping backslashes."""
        assert _cypher_escape("path\\to\\file") == "path\\\\to\\\\file"

    def test_escape_combined(self):
        """Test escaping multiple special chars."""
        assert _cypher_escape("It's a \\test") == "It\\'s a \\\\test"

    def test_escape_empty(self):
        """Test escaping empty string."""
        assert _cypher_escape("") == ""


class TestCypherValidity:
    """Tests for Cypher syntax validity."""

    def test_valid_cypher_structure(self, sample_graph):
        """Test that output has valid Cypher structure."""
        cypher = export_neo4j(sample_graph)
        lines = [l for l in cypher.split("\n") if l.strip() and not l.startswith("//")]

        for line in lines:
            # Each non-comment line should be CREATE or relationship
            assert line.startswith("CREATE") or line.strip() == ""

    def test_node_variable_consistency(self, sample_graph):
        """Test that node variables are used consistently in edges."""
        cypher = export_neo4j(sample_graph)

        # Extract node definitions
        node_vars = set()
        for line in cypher.split("\n"):
            if "CREATE (n" in line and ":" in line:
                # Extract variable name
                var = line.split("(")[1].split(":")[0]
                node_vars.add(var)

        # Extract edge source/target variables
        for line in cypher.split("\n"):
            if ")-[:" in line:
                # Extract source and target
                source = line.split("(")[1].split(")")[0]
                target = line.split("->")[1].split(")")[0].replace("(", "")
                assert source in node_vars, f"Unknown source variable: {source}"
                assert target in node_vars, f"Unknown target variable: {target}"


class TestEdgeCases:
    """Test edge cases."""

    def test_empty_graph(self):
        """Test exporting empty graph."""
        g = PropertyGraph()
        cypher = export_neo4j(g)
        assert "Nodes: 0" in cypher
        assert "Edges: 0" in cypher
        # Should only have header, no CREATE statements
        assert cypher.count("CREATE") == 0

    def test_node_with_special_chars(self):
        """Test node with special characters in label."""
        g = PropertyGraph()
        g.add_node(GraphNode(
            said="ESAID",
            node_type=NodeType.CREDENTIAL,
            label="Test's \"Credential\"",
        ))
        cypher = export_neo4j(g)
        # Single quotes should be escaped
        assert "Test\\'s" in cypher

    def test_numeric_properties(self):
        """Test nodes with numeric properties."""
        g = PropertyGraph()
        g.add_node(GraphNode(
            said="ESAID",
            node_type=NodeType.CREDENTIAL,
            key_state_seq=42,
            delegation_depth=2,
        ))
        cypher = export_neo4j(g)
        assert "key_state_seq: 42" in cypher
        assert "delegation_depth: 2" in cypher

    def test_edge_with_weight(self):
        """Test edge with numeric weight."""
        g = PropertyGraph()
        g.add_node(GraphNode(said="ESAID1", node_type=NodeType.CREDENTIAL))
        g.add_node(GraphNode(said="ESAID2", node_type=NodeType.CREDENTIAL))
        g.add_edge(GraphEdge(
            source_said="ESAID1",
            target_said="ESAID2",
            edge_type="acdc",
            weight=0.95,
        ))
        cypher = export_neo4j(g)
        assert "weight: 0.95" in cypher
